# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "hid_generic" "uas" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Bootloader for Raspberry Pi
  boot.loader.grub.enable = false;
  boot.loader.generic-extlinux-compatible.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Use mainline kernel to avoid building linuxPackages_rpi4 from source
  # (2.5h compile that exhausts VM disk space). Normal priority is sufficient
  # to override nixos-hardware's mkDefault without breaking its other settings.
  # USB/keyboard works because xhci_pci + usbhid are loaded via initrd above.
  boot.kernelPackages = pkgs.linuxPackages;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
