# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Bootloader for Raspberry Pi
  boot.loader.grub.enable = false;
  boot.loader.generic-extlinux-compatible.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Force the use of the standard mainline kernel instead of the Raspberry Pi specific fork.
  # The rpi fork is often missing from the binary cache, causing a 2.5 hour compilation from source
  # which runs out of disk space on the Linux VM.
  boot.kernelPackages = lib.mkForce pkgs.linuxPackages;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
